stages:

  - build
  - test
  - review
  - deploy
  - notify

before_script:

  - axneo system update
  - axneo system upgrade


Build Axon(s):

  stage: build

  tags:
    - axneo-r1

  script:
    - axneo build


Unit Test:

  stage: test

  tags:
      - axneo-r1

  script:
    - echo "Run Test"


Start Review:

  stage: review

  tags:
    - axneo-r1

  script:
    - axneo status

  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://axneo.axneoapps.com/$CI_BUILD_REF_NAME

  only:
    - branches

  except:
    - master


Stop Review:

  stage: review

  tags:
    - axneo-r1

  variables:
    GIT_STRATEGY: none

  script:
    - axneo shutdown

  when: manual

  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop

  only:
    - branches

  except:
    - master


Deploy Staging:

  stage: deploy

  tags:
    - axneo-r1

  script:
    - axneo deploy staging

  environment:
    name: staging
    url: https://staging.axneo.com

  only:
    - master


Deploy Production:

  stage: deploy

  tags:
    - axneo-r1

  script:
    - echo "Deploy to production server"

  environment:
    name: production
    url: https://www.axneo.com

  when: manual

  only:
    - master


Notify:

  stage: notify

  tags:
    - axneo-r1

  script:
    - echo "test"
