stages:

  - build
  - test
  - review
  - deploy
  - notify


Build Axon(s):

  stage: build
  script:
    - axneo build
    - cd ~/axneo.com
    - git checkout $CI_BUILD_REF_NAME
    - git pull
    - docker-compose -f axneo.yml down
    - docker-compose -f axneo.yml up -d --build


Test:

  stage: test
  script:
    - echo "Run Test"


Start Review:

  stage: review

  script:
    - echo "Deployment complete"

  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://axneo.axneoapps.com/$CI_BUILD_REF_NAME

  only:
    - branches

  except:
    - master


Stop Review:

  stage: review

  variables:
    GIT_STRATEGY: none

  script:
    - docker-compose -f axneo.yml down

  when: manual

  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop


deploy_staging:

  stage: deploy

  script:
    - echo "Deploy to staging server"

  environment:
    name: staging
    url: https://staging.axneo.com

  only:
    - master


deploy_production:

  stage: deploy

  script:
    - echo "Deploy to production server"

  environment:
    name: production
    url: https://www.axneo.com

  when: manual

  only:
    - master
