version: '2'
services:
   db:
     image: mysql:latest
     volumes:
       - database:/var/lib/mysql:rw
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    database:

#  app:
#    build:
#      context: ./bundle
#      dockerfile: axneo.docker
#
#    ports:
#      - "80:80"
#
#    restart: always