version: '2'

services:
#  db:
#    image: mariadb:${db_version}
#    volumes:
#      - ~/axneo.com/volumes/db:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: wordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
#
#  wordpress:
#    image: wordpress:${wp_version}
#    ports:
#      - "80:80"
#    depends_on:
#      - db
#    links:
#      - db
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress

app:
  build:
    context: ./bundle
    dockerfile: axneo.docker

  ports:
    - "80:80"

  restart: always